name: Cheat Monkey type 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        python-version: ["3.8", "3.10"]

    on: push

    steps:
      - uses: action/checkout@v3
      - name: Set Up Python ${{ matrix.python-version }}
        uses: action/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=150 --statistics
      
      - name: Test with unittest
        run: |
          python -m unittest ./simple_test.py


      
